name: firebase_app_distribution_platform_interface
description: A common platform interface for the firebase_app_distribution plugin.
version: 1.1.0
homepage: https://github.com/tpucci/firebase_app_distribution
repository: https://github.com/tpucci/firebase_app_distribution

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
