name: firebase_app_distribution
description: A Flutter plugin to enable testers to sign in and receive in-app updates.
version: 1.0.0
homepage: https://github.com/tpucci/firebase_app_distribution
repository: https://github.com/tpucci/firebase_app_distribution

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: firebase_app_distribution_android
      ios:
        default_package: firebase_app_distribution_ios

dependencies:
  firebase_app_distribution_android: 1.0.0
  firebase_app_distribution_ios: 1.0.0
  firebase_app_distribution_platform_interface: 1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^6.0.0
