name: firebase_app_distribution_ios
description: iOS implementation of the firebase_app_distribution plugin
version: 1.0.0
homepage: https://github.com/tpucci/firebase_app_distribution
repository: https://github.com/tpucci/firebase_app_distribution

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: firebase_app_distribution
    platforms:
      ios:
        pluginClass: FirebaseAppDistributionPlugin
        dartPluginClass: FirebaseAppDistributionIOS

dependencies:
  flutter:
    sdk: flutter
  firebase_app_distribution_platform_interface: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^6.0.0
